//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderVip
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> PVipID { get; set; }
        public int PaymentID { get; set; }
        public Nullable<int> OrdPrice { get; set; }
        public System.DateTime OrdDayCreate { get; set; }
    
        public virtual PackageVip PackageVip { get; set; }
        public virtual User User { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
