//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageVip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackageVip()
        {
            this.OrderVips = new HashSet<OrderVip>();
        }
    
        public int ID { get; set; }
        public string PVipName { get; set; }
        public int PVipMonths { get; set; }
        public int PVipPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderVip> OrderVips { get; set; }
    }
}
