//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int ID { get; set; }
        public string PartnerName { get; set; }
        public string PartnerImage { get; set; }
        public string PartnerLink { get; set; }
        public bool PartnerActive { get; set; }
        public System.DateTime PartnerDayCreate { get; set; }
    }
}
