//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityMusic
    {
        public int ID { get; set; }
        public int MusicID { get; set; }
        public string MusicFile { get; set; }
        public int QualityID { get; set; }
        public bool QMusicApproved { get; set; }
        public bool NewFile { get; set; }
    
        public virtual Quality Quality { get; set; }
    }
}
