//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankMusic
    {
        public int ID { get; set; }
        public int RankID { get; set; }
        public int MusicID { get; set; }
        public int RMusicGrade { get; set; }
    
        public virtual Music Music { get; set; }
    }
}
